include .env
export $(shell sed 's/=.*//' .env)

build:
	forge build

test:
	forge test -vvvv

deploy:
	forge script script/DeployDeBond.s.sol:DeployDeBond --rpc-url $(BASE_MAIN_NET_L2_URL) -vvv

fork-base:
	forge test --fork-url $(BASE_MAIN_NET_L2_URL) -vv