

export BASE_SEPOLIA_L2_URL=https://base-sepolia.g.alchemy.com/v2/JqXqj6fbWasALzV14Ha5T

build:
	forge build

test:
	forge test -vvvv

deploy:
	forge script script/DeployDeBond.s.sol:DeployDeBond --rpc-url $BASE_SEPOLIA_L2_URL -vvv

fork:
	forge test --fork-url BASE_SEPOLIA_L2_URL