name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        run: |
          curl -L https://foundry.paradigm.xyz | bash
          source ~/.bashrc
          foundryup

      - name: Show Forge version
        run: |
          cd .. 
          forge --version

 

      - name: Run Forge build
        run: |
          cd .. 
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          cd .. 
          forge test -vvv
        id: test
